# Generated by Django 3.2.7 on 2022-02-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220223_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Tether', 'Tether'), ('Solana', 'Solana'), ('XRP', 'XRP'), ('Dogecoin', 'Dogecoin'), ('Polkadot(DOT)', 'Polkadot(DOT)'), ('Other', 'OTHER')], default='Bitcoin', max_length=20)),
            ],
        ),
    ]
